apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnect
metadata:
  name: debezium-connect-cluster
  annotations:
    strimzi.io/use-connector-resources: "true"
spec:
  version: 3.6.1
  replicas: 1
  bootstrapServers: my-cluster-kafka-bootstrap:9093
  tls:
    trustedCertificates:
      - secretName: my-cluster-cluster-ca-cert
        certificate: ca.crt
  config:
    group.id: connect-cluster
    offset.storage.topic: connect-cluster-offsets
    config.storage.topic: connect-cluster-configs
    status.storage.topic: connect-cluster-status
    # -1 means it will use the default replication factor configured in the broker
    config.storage.replication.factor: -1
    offset.storage.replication.factor: -1
    status.storage.replication.factor: -1
  
  # First make build, and then after successfull push to docker comment the below lines
  
  build:
    output:
      type: docker
      image: index.docker.io/developer9844/kafka-connect-example:2.0
      pushSecret: myregistrykey
    plugins:
      - name: debezium-mysql-connector
        artifacts:
          - type: tgz
            # we specify the location(URL) from which to fetch the necessary artifact for the build process. 
            # In this particular case, the artifact being fetched is a tarball (tgz type) containing the Debezium MySQL Connector plugin. 
            url: https://repo1.maven.org/maven2/io/debezium/debezium-connector-mysql/2.4.0.Final/debezium-connector-mysql-2.4.0.Final-plugin.tar.gz