apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnector
metadata:
  name: debezium-mysql-connector
  labels:
    strimzi.io/cluster: debezium-connect-cluster
spec:
  class: io.debezium.connector.mysql.MySqlConnector
  tasksMax: 1
  config:
    tasks.max: 1
    database.hostname: mysql.default.svc.cluster.local
    database.port: 3306
    database.user: root
    database.password: debezium
    database.server.id: 223344
    database.server.name: mysql
    topic: my-topic
    topic.prefix: mysql
    database.include.list: inventory  # database name
    schema.history.internal.kafka.bootstrap.servers: my-cluster-kafka-bootstrap:9092
    schema.history.internal.kafka.topic: schema-changes.inventory
    



