apiVersion: apps/v1
kind: Deployment
metadata:
  name: debezium-ui
  namespace: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: debezium-ui
  template:
    metadata:
      labels:
        app: debezium-ui
    spec:
      containers:
      - name: debezium-ui
        image: quay.io/debezium/debezium-ui:2.4
        resources:
            requests:
              memory: "128Mi"
              cpu: "25m"
            limits:
              memory: "512Mi"
              cpu: "150m"
        ports:
        - containerPort: 8080
        env:
        - name: KAFKA_CONNECT_URIS
          value: "http://debezium-connect-cluster-connect-api:8083"

---
apiVersion: v1
kind: Service
metadata:
  name: debezium-ui
spec:
  selector:
    app: debezium-ui
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      