apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: my-cluster-2
  namespace: kafka
spec:
  kafka:
    version: 3.6.0
    replicas: 2
    listeners:
    - name: tls
      port: 9093
      type: internal
      tls: true
      authentication:
        type: scram-sha-512
    authorization:
      type: simple
    config:
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
      default.replication.factor: 1
      min.insync.replicas: 1
      inter.broker.protocol.version: "3.6"
    storage:
      type: jbod
      volumes:
      - id: 0
        type: persistent-claim
        size: 100Gi
        deleteClaim: false
    resources:
      requests:
        memory: "128Mi"
        cpu: "0.5m"
      limits:
        memory: "200Mi"
        cpu: "1m"
  zookeeper:
    replicas: 2
    storage:
      type: persistent-claim
      size: 10Gi
      deleteClaim: false
    resources:
      requests:
        memory: "128Mi"
        cpu: "0.5m"
      limits:
        memory: "200Mi"
        cpu: "0.7m"
  entityOperator:
    topicOperator: {}
    userOperator: {}


